spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:posdb}
    username: ${DB_USER:pos_user}
    password: ${DB_PASSWORD:pos_user}
  jpa:
    properties:
      hibernate.default_schema: pos
  application:
    name: pos-system
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: pos
